services:
  postgres:
     container_name: postgres
     image: postgres
     restart: unless-stopped
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=admin
     volumes:
       - postgres:/data/postgres
     networks:
       - postgres
# open localhost:5050/browser/ to view, enter host name is postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgamin4@gmail.com}
       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
       PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    networks:
       - postgres
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin: